### ISSUE TITLE
Slider scale labels

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#1895]
Would be nice to have scale labels for the [Slider](https://www.primefaces.org/primevue/showcase-v2/#/slider) like shown bellow:

![image](https://user-images.githubusercontent.com/13495631/146207088-2e57e675-53f4-4b30-bcba-29bca54430c4.png)

![image](https://user-images.githubusercontent.com/13495631/146206978-f54e4bba-73da-4767-b4ff-1772b8c9ec50.png)

Thanks.

**Comment by henckellSop** [comment]
Indeed! This would be really great!

**Comment by henckellSop** [comment]
Maybe also a Tooltip would be helpful: 
![Slider-tooltip](https://user-images.githubusercontent.com/98587584/158763978-0613d6aa-d386-45a7-a0a4-72998fa4a337.png)

**Comment by tirtasantoso** [comment]
this feature will be good to have.  +1

**Comment by sanderdewinter** [comment]
@henckellSop since there is attributue `ariavalue-now` on the slider handle you can easily add this using `::before` pseudo-element like so:
 ```css
.p-slider-sliding::before {
    content: attr(aria-valuenow);
    position: absolute;
    bottom: 100%;
}
```
