### ISSUE TITLE
DataTable Column Resizing incompatible with Column Reordering

### ISSUE THREAD

**Issue by nclemeur** [primefaces/primevue#2188]
```
[x ] bug report
```
**CodeSandbox Case (Bug Reports)**

Use example in https://www.primefaces.org/primevue/showcase/#/datatable/reorder and simply add `:reorderable-columns="true"` to the `DataTable` components

**Current behavior**
After a column resize,  any reordered column will have the width of the column it replace.

**Expected behavior**
The reordered column should keep the width it had before the reordering

**Minimal reproduction of the problem with instructions**
In the example above:
1. Resize the column `Name`  so that it noticeably smaller than the `Code` column
2. Move the `Code` column before the ` Name` column
   => Column `Name` has now the width of the column `Code` and vice-versa

**Comment by nclemeur** [comment]
It seems that column resizing is also not working when toggling columns on and off. If any resize happen, hiding a column after that, will have some impact on the size of columns after the column that has just been hidden...

**Comment by ShadowZone** [comment]
Still important in 2023 for our production system 👍 Is there maybe a workaround for the time beeing?

**Comment by vladimir-econom** [comment]
I've faced the same issue.
Looks like the problem relates to resizable feature - when it true - the width of the style of the TH configures by the resize event and produce the following class
```css
.p-datatable[pv_id_5] > .p-datatable-wrapper > .p-datatable-table > .p-datatable-thead > tr > th:nth-child(6), 
.p-datatable[pv_id_5] > .p-datatable-wrapper > .p-datatable-table > .p-datatable-tbody > tr > td:nth-child(6), 
.p-datatable[pv_id_5] > .p-datatable-wrapper > .p-datatable-table > .p-datatable-tfoot > tr > td:nth-child(6) {
    width: 153px !important;
    max-width: 153px !important;
}
```

So when the order of the columns changes - this class does not.
The only workaround in this case is not to use these 2 features together (

I've resolved my case using column-resize-mode="expand" for DataTable and style `min-width: max-content` for table-cell content.
