### ISSUE TITLE
DataTable: scrollable breaks ColumnGroup header layout

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#3114]
### Describe the bug

Header columns do not align with the body columns,
![image](https://user-images.githubusercontent.com/8471027/195580397-7b66cb0f-6312-4f28-976b-54b42564d7ce.png)

### Reproducer

https://codesandbox.io/s/weathered-resonance-sifrp3?file=/src/DataTableDemo.vue

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1.add a ColumnGroup type="header" with two rows to the datatable
2.add :scrollable="true" to the datatable
3.set width on a column in second row -> it's applied to the body cell but not to the header cell

### Expected behavior

header columns should be correctly aligned with the body columns.
It works if you remove the scrollable prop.

**Comment by Rakasch** [comment]
By the way:
When I add `:virtualScrollerOptions="{ itemSize: 50 }"` to the reproducer example, the Datatable is not rendering anymore.
I only get a white page.
Not sure if that's a codesandbox issue. It does work for me in my own local code.

**Comment by Rakasch** [comment]
Just as an idea.
Maybe html colgroups could help with this issue.
eg. https://www.w3schools.com/tags/tag_colgroup.asp

**Comment by gigizhaoo** [comment]
@Rakasch  原因是scrollable=true状态下display被修改了 
 ```css
:global(.p-datatable-scrollable .p-datatable-tbody > tr) {
  display: table-row;
}
:global(.p-datatable-scrollable .p-datatable-tbody > tr > td) {
  display: table-cell;
}
```
