### ISSUE TITLE
[InputNumber] can't align number to right

### ISSUE THREAD

**Issue by thichnguyen** [primefaces/primevue#344]
In version 2.6.10, InputNumber component that is align left as default.
Can't change CSS to align-right.

How to change it when using this component?

**Comment by cagataycivici** [comment]
```css
.p-inputnumber {
    text-align: right,
}
```
