### ISSUE TITLE
Ability to change animations of components using custom css or animate css

### ISSUE THREAD

**Issue by nanaaikinson24** [primefaces/primevue#371]
Is there a way to change the animation of some components such toasts, dialogs etc

**Comment by cagataycivici** [comment]
Yes, with CSS, please use our forum for questions, we may come up with an example eg. on a dialog;

https://forum.primefaces.org/viewforum.php?f=110

Current one is;

```css
.p-dialog-enter-active {
    transition: all 150ms cubic-bezier(0, 0, 0.2, 1);
}
.p-dialog-leave-active {
    transition: all 150ms cubic-bezier(0.4, 0.0, 0.2, 1);
}
.p-dialog-enter,
.p-dialog-leave-to {
    opacity: 0;
    transform: scale(0.7);
}
```

With an override, you can change it.
