### ISSUE TITLE
DataTable: responsive layout for mobile prop

### ISSUE THREAD

**Issue by MargaritaBusyginaCa** [primefaces/primevue#4131]
### Describe the feature you would like to see added

In version 3.23.0 DataTable component has a nice responsive design and it looks good on all screens.
I noticed that in version 3.24.0 responsive design is removed. Is there a reason for that?
I was wondering if maybe you can add a prop "responsive". If it's set to true, then the mobile design looks like in version 3.23.0.

### Is your feature request related to a problem?

We already built a data table with the accustomed responsive design and the current version breaks all of it. We will try to fix it, but I am not sure why such a big design change was made in the later versions. Would be great if there was an option for that.

### Additional context

Version 3.23.0
![Screenshot 2023-07-12 at 1 21 26 PM](https://github.com/primefaces/primevue/assets/74435192/20334d72-0579-4f9c-9ad6-8f0f8513b53b)
The latest version (3.30)
![Screenshot 2023-07-12 at 1 21 05 PM](https://github.com/primefaces/primevue/assets/74435192/7752ba36-f76b-44c6-9085-d6e665422f52)

**Comment by NsdHSO** [comment]
@MargaritaBusyginaCa I tried right now in the isolated env, and works fine, can you share your env ???

**Comment by MargaritaBusyginaCa** [comment]
@NsdHSO any CodeSand sample from PrimeVue's DataTable page has the same result of the table not being responsive. Here is one of the examples: https://codesandbox.io/s/jvs6vq

Also, here is the sample code I used to test it:
```
<script setup>
import { ref } from 'vue';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
const data = ref([
	{ name: 'James', age: 24, job: 'Manager', department: 'Marketing' },
	{ name: 'Jill', age: 26, job: 'Engineer', department: 'IT' },
	{ name: 'Elyse', age: 24, job: 'Designer', department: 'IT' },
	{ name: 'Elsa', age: 34, job: 'Designer', department: 'Marketing' },
	{ name: 'Mike', age: 30, job: 'Human Resources', department: 'Human Resources' }
]);
</script>

<template>
	<div class="card">
		<DataTable :value="data">
			<Column field="name" header="name"></Column>
			<Column field="age" header="age"></Column>
			<Column field="job" header="job"></Column>
			<Column field="department" header="department"></Column>
		</DataTable>
	</div>
</template>
```

**Comment by NsdHSO** [comment]
I tried in your env, and it looks [good](https://codesandbox.io/s/primevue-demo-forked-zfkc32?file=/src/App.vue&resolutionWidth=216&resolutionHeight=661).

**Comment by NsdHSO** [comment]
IMHO this detail is so cute, but I think you are free to implement this logic at some breakpoint of view some columns don't show. We have some alternative one of them are `@vueuse/core` [here](https://codesandbox.io/s/primevue-demo-forked-7m9kgz?resolutionWidth=602&resolutionHeight=622) you can see my approach.

**Comment by engel-m** [comment]
Any update? The responsive stacked layout is indeed completely missing after 3.23.0, which is very strange since it worked very well. I am now back to version 3.23.0 only for this feature. 

Removing columns at breakpoints is a very poor workaround solution in comparison to the responsive layout that existed, and not viable for a lot of use cases.

**Comment by MargaritaBusyginaCa** [comment]
@engel-m @NsdHSO 
I agree that a scrollable table is a poor user experience. It is not responsive or accessible.
I would really appreciate it if an option to turn on/off responsive design was added. Having a workaround to achieve the same design as in version 3.23 will complicate the code, which should always be avoided unless necessary.

**Comment by RickKukiela** [comment]
I am trying to pick a UI framework for a new HUGE passion project of mine that I am going to start and this is one of my requirements - that a table can be be "stacked" via an alternate "card style" layout for mobile users, rather than forcing horizontal scrolling.

It seems that none of the current UI libraries I have checked support this feature anymore.

In the past I have used Vuetify that had this feature (which is where I first learned about the concept and possibility of doing such a thing) but even their current DOCs have a blatant omission of this feature and viewing their component pages in a mobile emulated screen session does not show this feature is active on any of the demo tables.

This is the same situation with Prime here, as none of the demo tables on the components docs have this interaction.

Since none of the modern UI frameworks appear to do this anymore I'm probably going to try Prime anyway as I'm in the mood for something new and this framework seems pretty capable.

I sincerely hope this feature is re-added at some point though, as I feel its a huge let down to not support something so much better for mobile users than forcing us to hide columns  and/or requiring horizontal scrolling. Both of which are poor UI choices for mobile users.

**Comment by levarberry** [comment]
What I ended up doing.    Making 2  Components ( DataTable and DataView)  and using CSS media selector to display or hide each accordingly.    Sucks to have to write it twice, but a minor 15 minute additional work to get the exact results needed.

**Comment by RickKukiela** [comment]
@levarberry Yeah that's one work around. It's kind of like what we used to do back in the day where we would have a large image for desktop and a small image for mobile and use media queries to show one or the other. Now-days we can use the `<picture>` tag so the browser only downloads the appropriate image and bandwidth isn't wasted. The same type of problem comes up with this work around as it will in some ways cause extra bloat by needing to load all of the HTML twice so the media query can swap it out, on top of the added `technical debt` of having to program it twice and manage it in both places going forward... Ideally they would return the missing functionally that they apparently removed without reason (or at least providing a reason).

**Comment by san-kumar** [comment]
You can use CSS to render the table responsively on mobile devices. Unfortunately sorting, filters, etc stop working. But it's a good option for simple use cases without adding any extra logic like this:

Example:

```css
@media (max-width: 767px) {
    #dt-responsive-table table {
        width: 100% !important;
    }

    /* Styles for the table header */
    #dt-responsive-table table thead {
        display: none !important; /* Hide the table header on mobile */
    }

    /* Styles for the table rows */
    #dt-responsive-table table tbody {
        display: flex !important;
        flex-direction: column !important;
        align-items: stretch !important;
        min-height: auto !important; /* Adjust the min-height as needed */
    }

    /* Styles for individual table rows (cards) */
    #dt-responsive-table table tbody tr {
        border: 1px solid #ccc !important;
        border-radius: 8px !important;
        margin-bottom: 1rem !important;
        background-color: #fff !important;
        padding: 1rem !important;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1) !important;
    }

    /* Styles for table cells within rows */
    #dt-responsive-table table tbody td {
        margin: 0.5rem 0 !important;
    }

    /* Hide individual table rows (cards) on mobile */
    #dt-responsive-table table tbody tr {
        display: table-row !important;
    }

    /* Set the display of table cells to be block-level elements */
    #dt-responsive-table table tbody td {
        display: block !important;
        margin: 0.5rem 0 !important;
    }
}
```

To use this, just add `id="dt-responsive-table"` to your DataTable component.
