### ISSUE TITLE
Styling missing after upgrading to PrimeVue 3.35.0

### ISSUE THREAD

**Issue by luke-z** [primefaces/primevue#4529]
### Describe the bug

Today I updated my project to the newest version of PrimeVue. 
Since then all PrimeVue styles are missing and everything looks unstyled.

If I remove the ```@nuxtjs/tailwindcss``` module, the PrimeVue styling works again.
Using unstyled mode and tailwind passthrough doesn't make a difference.

Adding the path ```"./node_modules/primevue/**/*.{vue,js,ts,jsx,tsx}"``` to the content array in ```tailwind.config.ts``` also doesn't help.

It works with previous versions of PrimeVue up to and including 3.34.1.

### Reproducer

https://codesandbox.io/p/sandbox/lucid-platform-h5q29w?welcome=true

### PrimeVue version

3.35.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Firefox, Edge, Brave, Chrome

### Steps to reproduce the behavior

Open up the sandbox and see that the Primevue Button is missing styling, only the font is a little different.

### Expected behavior

The button should be using the normal lara light blue theme and thus be blue with white font.

**Comment by cagataycivici** [comment]
This seems to be an example of;

https://www.youtube.com/watch?v=EPRUy0lvgBA&t=202s

Tailwind is clearing Prime CSS in styled mode;

```css
button, [type='button'], [type='reset'], [type='submit'] {
    -webkit-appearance: button;
    background-color: transparent;
    background-image: none;
}
```
