### ISSUE TITLE
Button: "raised" props loses shadow when button is clicked and "severity" props is also included

### ISSUE THREAD

**Issue by munkeywolf00** [primefaces/primevue#5401]
### Describe the bug

Button component with "raised" props loses shadow when button is clicked and "severity" props is also included. The shadow then returns when out of focus. I am not sure if this is intended.

### Reproducer

https://stackblitz.com/run?file=src%2FApp.vue

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Firefox 123.0.1

### Steps to reproduce the behavior

1. Go to: https://primevue.org/button/
2. See Raised prop samples
3. Click first button. It does not lose shadow on click
4. Click other button that has severity, it loses the shadow. Click out of the button, it shows the shadow back.

### Expected behavior

Button with "raised" prop should retain the shadow when clicked even if "severity" prop is also present.

**Comment by tugcekucukoglu** [comment]
In this screenshot, all these buttons have active state and shadows of them are visible. Am I missing something?

<img width="1091" alt="raised-button" src="https://github.com/primefaces/primevue/assets/32294991/e2252cbb-c6b8-41f2-86ce-60ad483bb5be">

**Comment by munkeywolf00** [comment]
> In this screenshot, all these buttons have active state and shadows of them are visible. Am I missing something?
> 
> <img width="1091" alt="raised-button" src="https://github.com/primefaces/primevue/assets/32294991/e2252cbb-c6b8-41f2-86ce-60ad483bb5be">
> 

Sorry. Please try to click other buttons. Like secondary. The shadow is gone. Which I am not sure if intended.

**Comment by MiAnMy** [comment]
Some classes have box-shadow removal on click. For example here
 ```css
  .p-button.p-button-success:not(:disabled):focus, .p-button-group.p-button-success > .p-button:not(:disabled):focus, .p-splitbutton.p-button-success > .p-button:not(:disabled):focus {
    box-shadow: none;
  }
```
