### ISSUE TITLE
Component Name: Button group not working with as=router-link in button

### ISSUE THREAD

**Issue by iimrudy** [primefaces/primevue#6557]
### Describe the bug

The button group component does not work if one of the button has the attribute 'as="router-link"'

code example used

```
                        <ButtonGroup>
                            <Button as="router-link" size="small"
                                icon="pi pi-eye" :to="{ name: 'job_details', params: { id: data.id } }"/>
                            <Button
                                     @click="stopJob(data.id)" size="small" severity="danger" icon="pi pi-stop" />
                        </ButtonGroup>
```
result behavior image
![image](https://github.com/user-attachments/assets/6e3a4a0c-9569-4051-a3c7-cddade5914c7)

expected behavior image (removing the as=router-link works fine)

![image](https://github.com/user-attachments/assets/c95a0cbf-bdbe-4af4-b177-645e1a7050c3)

### Reproducer

can't reproduce it here

### PrimeVue version

4.1.0

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Microsoft Edge Version 129.0.2792.79 (Official build) (64-bit). but i think that happens with all browser

**Comment by CCodam** [comment]
You can use the InputGroup instead, it works with buttons too.
The InputGroup uses **only/first/last-child** instead of **only/first/last-of-type**.

Consider deprecating the ButtonGroup in favour of the InputGroup.
Consider changing the CSS to use **only/first/last-child** on the ButtonGroup.
_Change at buttongroup/style/ButtonGroupStyle.js line 13-25_
```css
.p-buttongroup .p-button:not(:first-child):not(:last-child) {
    border-radius: 0;
}
.p-buttongroup .p-button:first-child:not(:only-child) {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}
.p-buttongroup .p-button:last-child:not(:only-child) {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
}
```

Also, SplitButton is not styled correctly within a ButtonGroup nor an InputGroup.
Consider the following CSS additions for the SplitButton to be styled correctly within a ButtonGroup.
_Merge with existing blocks at buttongroup/style/ButtonGroupStyle.js line 13-25_
```css
.p-buttongroup .p-splitbutton:not(:first-child):not(:last-child) .p-button {
    border-radius: 0;
}
.p-buttongroup .p-splitbutton:first-child:not(:only-child) .p-button {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}
.p-buttongroup .p-splitbutton:last-child:not(:only-child) .p-button {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
}
```
Consider the following CSS additions for the SplitButton to be styled correctly within a InputGroup.
_Merge with existing blocks at buttongroup/style/ButtonGroupStyle.js line 39-69_
```css
.p-inputgroup > .p-splitbutton > .p-component {
    border-radius: 0;
    margin: 0;
}
.p-inputgroup > .p-splitbutton:first-child > .p-component:first-child {
    border-top-left-radius: var(--p-inputgroup-addon-border-radius);
    border-bottom-left-radius: var(--p-inputgroup-addon-border-radius);
}
.p-inputgroup > .p-splitbutton:last-child > .p-component:last-child {
    border-top-right-radius: var(--p-inputgroup-addon-border-radius);
    border-bottom-right-radius: var(--p-inputgroup-addon-border-radius);
}
```
