### ISSUE TITLE
Invalid CSS in DataTable and TreeTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primevue#6580]
```css
p-treetable-gridlines .p-treetable-tbody > tr:last-child > td {
    border-width: 1px 0 1px 1px;
}
```

Missing dot
