### ISSUE TITLE
[FEATURE REQUEST] - Divider/Separator Component

### ISSUE THREAD

**Issue by go4cas** [primefaces/primevue#690]
Indicator to separate content.

Example: [AntD](https://2x.antdv.com/components/divider).

**Comment by cagataycivici** [comment]
Set to 3.0.3

**Comment by cagataycivici** [comment]
![screely-1606572028837](https://user-images.githubusercontent.com/686247/100517398-54f58300-319b-11eb-9270-cca1caa647cc.png)
![screely-1606572054938](https://user-images.githubusercontent.com/686247/100517401-5921a080-319b-11eb-9b6f-5d7b7cf92e3c.png)

**Comment by hscstudio** [comment]
I dont know why my divider not show line? I have checked in browser console, generated this html

```
<div class="p-divider p-component p-divider-horizontal p-divider-dashed p-divider-left" role="separator"><!----></div>
```

and in css console

```css
.p-divider-dashed.p-divider-horizontal:before {
    border-top-style: dashed;
}
```

I dont know why this css show in linethrough <s>border-top-style: dashed;</s>

**Comment by hscstudio** [comment]
> I dont know why my divider not show line? I have checked in browser console, generated this html
> 
> ```
> <div class="p-divider p-component p-divider-horizontal p-divider-dashed p-divider-left" role="separator"></div>
> ```
> 
> and in css console
> 
> ```css
> .p-divider-dashed.p-divider-horizontal:before {
>     border-top-style: dashed;
> }
> ```
> 
> I dont know why this css show in linethrough border-top-style: dashed;

For temporary solution, I override css style in component
```css
.p-divider-solid.p-divider-horizontal:before {
  border-top-style: solid !important;
}
.p-divider-dashed.p-divider-horizontal:before {
  border-top-style: dashed !important;
}
.p-divider-solid.p-divider-vertical:before {
  border-left-style: solid !important;
}
```
