### ISSUE TITLE
Issue with primevue package

### ISSUE THREAD

**Issue by TylerWanta** [primefaces/primevue#7298]
### Describe the bug

I need to make some quick tweaks to the repo for my project. Because of this, I am trying to fork and publish the repo but am running into some issues. All I've done so far is change the name of the primevue package as well as create a github action to publish. Upon running the action, I get this error 

<img width="1052" alt="Image" src="https://github.com/user-attachments/assets/c168e8a8-56aa-4a15-9293-4cf7681052ea" />

It looks like the build is failing while running `pnpm run release` on the monorepo. I'm guessing this means there are more nuances to the publishing process that I don't know about.

Here is my publish action: 
```
name: Publish Package to npmjs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
            version: 9.6.0

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - run: |
            pnpm run setup
            pnpm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```
Trying to publish it manually within VS Code gives a similar error.

<img width="1228" alt="Image" src="https://github.com/user-attachments/assets/64f867bc-2a43-4ed4-9ae1-c8d01dbc3a43" />

Would you please be able to explain how PrimeTek publishes the primevue package to npm, or provide a .yaml github action to accomplish it? I'd be more than happy to help document this process afterwards for future users.

Link to the forked repo: https://github.com/TylerWanta/primevue-tw

### Reason for not contributing a PR

- [ ] Lack of time
- [ ] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [x] Other

### Other Reason

Not relevant

### Reproducer

https://github.com/TylerWanta/primevue-tw

### Environment

Forked Repo is all

### Vue version

n.a

### PrimeVue version

v4

### Steps to reproduce the behavior

Clone My repo and run the publish action

### Expected behavior

Publish process is documented somewhere
