### ISSUE TITLE
PrimeVue 4.x Dark Mode Switching Not Working with Tailwind CSS 4.x and `.app-dark` Selector

### ISSUE THREAD

**Issue by xaero7** [primefaces/primevue#7465]
I'm working on a Vue project that uses PrimeVue with a custom theme (`Chocolatey`) and Tailwind CSS 4.x for styling. My goal is to implement dark mode switching using the `.app-dark` class, as specified in PrimeVue's `darkModeSelector` option. 

Demo is here : https://stackblitz.com/~/github.com/xaero7/vue3test

## Problem
Click the `sun` icon button, the background can turn to dark, but the card background can not.
HTML works well, When toggling the `.app-dark` class on the `<html>` element.
By checking the generated css code, I find the `Card` component background is:
```css
@media (prefers-color-scheme: dark) {
  :root {
    --p-content-background: var(--p-surface-900);
  }
```
If I change the generated  css code to:
```css
  .app-dark {
    --p-content-background: var(--p-surface-900);
  }
```
It can works well! But my code can't generate `.app-dart{ --p-content-background: var(--p-surface-900); }`, it remains stuck on code `@media (prefers-color-scheme: dark) { ... --p-content-background: var(--p-surface-900); ... }`

Is there a specific configuration step I’m missing to ensure PrimeVue’s dark mode respects the `.app-dark` selector?
Could Tailwind CSS 4.x still be interfering with PrimeVue’s theme switching despite disabling `prefers-color-scheme`?

Demo is here : https://stackblitz.com/~/github.com/xaero7/vue3test
