### ISSUE TITLE
Tooltip: Visual bug with rounded corners when tooltips are shifted/repositioned

### ISSUE THREAD

**Issue by stepanroznik** [primefaces/primevue#7829]
### Describe the bug

This is a follow-up to #7532 (Tooltip: shifts left), which fixed the positioning logic but did not fix the visual issues with rounded tooltips that were also mentioned.

When tooltips are repositioned due to screen constraints, the arrow appears directly at the rounded corner of the tooltip, creating a broken/ugly appearance.

**Current behavior:**
- Tooltips with `border-radius` look broken when repositioned
- No way to fix this styling issue as there are no CSS classes to target repositioned tooltips

### Solution 1: Add CSS Classes (Preferred)
Give developers an option to add CSS classes to identify repositioned tooltips so that they can fix the visual bug:

Example class names:
- `tooltip-repositioned` - Applied when tooltip position is adjusted
- `tooltip-repositioned-left` - Applied when shifted left due to right edge constraint
- `tooltip-repositioned-right` - Applied when shifted right due to left edge constraint

```html
<!-- Normal centered tooltip -->
<div class="tooltip tooltip-top" ...>
  <div class="tooltip-arrow" style="left: 50%"></div>
</div>

<!-- Edge-repositioned tooltip -->
<div class="tooltip-top tooltip-repositioned tooltip-repositioned-left" ...>
  <div class="tooltip-arrow" style="left: 494px"></div>
</div>
```

```css
/* Custom styling for repositioned tooltips */
.tooltip-top.tooltip-repositioned-left {
  /* Remove rounding where arrow touches corner */
  border-bottom-left-radius: 0;
}

.tooltip-top.tooltip-repositioned-right {
  /* Remove rounding where arrow touches corner */
  border-bottom-right-radius: 0;
}

.tooltip-bottom.tooltip-repositioned-left {
  border-top-left-radius: 0;
}
```

### Solution 2: Automatic Positioning Fix
Alternatively, adjust the positioning logic to prevent arrows from appearing at rounded corners:
- Add automatic offset when repositioning to keep arrows away from corners
- Provide a custom offset configuration option for finer control over tooltip placement relative to the target element
- This would automatically fix the visual bug without requiring CSS changes

## Related Issues
- #7532 - Original tooltip positioning issue (resolved positioning, styling concerns remain)

### Reason for not contributing a PR

- [ ] Lack of time
- [x] Unsure how to implement the fix/feature
- [x] Difficulty understanding the codebase
- [ ] Other

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-m4asqe8u

### Environment

Chrome 137

### Vue version

3.5.16

### PrimeVue version

4.3.5

### Node version

22.15.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Create a tooltip with the top position
2. Resize the viewport to a smaller width so that the tooltip does not have enough space to be centered above the element
3. Observe that the tooltip shifts to the left and the arrow appears directly at the rounded corner, creating a visually broken appearance

### Expected behavior

Repositioned tooltips should not have visual artifacts where arrows intersect with rounded corners. Either:

1. The tooltip positioning should account for rounded corners, or
2. CSS classes (or other means) should be provided to allow developers to fix the styling
