### ISSUE TITLE
p-button-link not visible in Material Design themes

### ISSUE THREAD

**Issue by blurbiness** [primefaces/primevue#852]
In Material Design themes, the CSS for `.p-button-link` is:
```CSS
.p-button.p-button-link {
  color: transparent;
  background: transparent;
  border: transparent;
}
```

All is transparent, so the button is completely hidden.
You can reproduce the behaviour in the showcase page:
https://primefaces.org/primevue/showcase/#/button

Pay attention to the basic link button. If you select a material design theme, it will dissapear.
