### ISSUE TITLE
Dialog is too small on mobile screen

### ISSUE THREAD

**Issue by denis-pujdak-adm-it** [primefaces/primevue#88]
The dialog looks very small on the mobile version of the screen. Please see the screenshot bellow:
![image](https://user-images.githubusercontent.com/13495631/69169986-3329e080-0af1-11ea-8bdb-766497990a59.png)

**Comment by cagataycivici** [comment]
You can write a media query to adjust it. Here is one example using a style class like **.mydialog**;

```xml
<Dialog class="mydialog" header="Dialog Header" :visible.sync="display"  :modal="true">
  //content
</Dialog
```

```css
<style scoped>
.mydialog {
    width: 50vw;
}

@media screen and (max-width: 60em) {
    .mydialog {
        width: 75vw;
    }
}
</style>
```
